// Self-check for WordMatcher. Run via build.sh.
var m = WordMatcher(script: "Thanks for joining me today. I want to walk you through three things.")
m.feed(transcript: "thanks for joining")
assert(m.position == 3, "matched first three words")
m.feed(transcript: "thanks for joining me today I want")
assert(m.position == 7, "partial results extend the tail")
m.feed(transcript: "thanks for joining me today I want um to walk")
assert(m.position == 9, "filler word is skipped")
m.feed(transcript: "thanks for joining me today I want um to walk banana")
assert(m.position == 9, "unmatched word does not move")
m.newSession()
m.feed(transcript: "you through")
assert(m.position == 11, "new session continues from position")
assert(abs(m.fraction - 11.0 / 13.0) < 0.001)
m.reset()
assert(m.position == 0)
print("WordMatcher ok")
